GET  http://localhost:5000/api/v1/orders/search
Content-Type: application/json

{
    "start_order_time": "2023-01-02",
    "end_order_time": "2024-01-03"
}
    
###

GET  http://localhost:5000/api/v1/orders/search
Content-Type: application/json

{
    "user_id": "abc123",
    "start_order_time": "2023-01-02",
    "end_order_time": "2024-01-03"
}

###

GET  http://localhost:5000/api/v1/orders/search
Content-Type: application/json

{
    "start_order_time": "2023-01-02",
    "user_id": "fed890",
    "end_order_time": "2024-01-03"
}

###

GET  http://localhost:5000/api/v1/orders/search
Content-Type: application/json

{
    "start_order_time": "2025-01-02",
    "user_id": "fed890",
    "end_order_time": "2025-01-03"
}